# Generated by Django 5.2.14 on 2026-05-28 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoFuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='importaciones/%Y/%m/', verbose_name='archivo')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='nombre original')),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX'), ('TXT', 'TXT')], max_length=8, verbose_name='tipo')),
                ('texto_extraido', models.TextField(blank=True, verbose_name='texto extraído')),
                ('estado', models.CharField(choices=[('SUBIDO', 'Subido'), ('PROCESADO', 'Procesado'), ('CONVERTIDO_A_CASO', 'Convertido a caso'), ('RECHAZADO', 'Rechazado')], default='SUBIDO', max_length=24, verbose_name='estado')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_fuente', to='casos.caso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivos_importados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo fuente',
                'verbose_name_plural': 'Archivos fuente',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
