# Generated by Django 5.2.14 on 2026-05-28 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctas', models.PositiveIntegerField(default=0, verbose_name='respuestas correctas')),
                ('incorrectas', models.PositiveIntegerField(default=0, verbose_name='respuestas incorrectas')),
                ('no_respondidas', models.PositiveIntegerField(default=0, verbose_name='preguntas sin responder')),
                ('peso_obtenido', models.PositiveIntegerField(default=0, verbose_name='peso obtenido')),
                ('peso_total', models.PositiveIntegerField(default=0, verbose_name='peso total del caso')),
                ('nota_final', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='nota final')),
                ('feedback_docente', models.TextField(blank=True, verbose_name='feedback general del docente')),
                ('notificado_estudiante', models.BooleanField(default=False, verbose_name='notificado al estudiante')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True, verbose_name='fecha del cálculo')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('participacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='participaciones.participacion')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
                'ordering': ['-fecha_calculo'],
            },
        ),
    ]
