# Generated by Django 5.2.15 on 2026-06-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_correo_smtp_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo_smtp_password',
            field=models.CharField(blank=True, help_text='Contraseña de aplicación Gmail (misma cuenta que email).', max_length=128, verbose_name='clave SMTP del correo'),
        ),
    ]
