# Generated by Django 5.2.14 on 2026-05-28 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('casos', '0001_initial'),
        ('practicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(blank=True, null=True, verbose_name='inicio')),
                ('fin', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('tiempo_usado_seg', models.PositiveIntegerField(default=0, verbose_name='tiempo usado (segundos)')),
                ('estado', models.CharField(choices=[('NO_INICIADA', 'No iniciada'), ('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada'), ('INCOMPLETA', 'Incompleta')], default='NO_INICIADA', max_length=20, verbose_name='estado')),
                ('autorizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participacion', to='practicas.autorizacionestudiante')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='academico.estudiante')),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='practicas.practica')),
            ],
            options={
                'verbose_name': 'Participación',
                'verbose_name_plural': 'Participaciones',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaSeleccionada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('participacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_seleccionadas', to='participaciones.participacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos.pregunta')),
                ('respuesta_elegida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos.respuesta')),
            ],
            options={
                'verbose_name': 'Respuesta seleccionada',
                'verbose_name_plural': 'Respuestas seleccionadas',
                'constraints': [models.UniqueConstraint(fields=('participacion', 'pregunta'), name='unique_respuesta_por_pregunta_participacion')],
            },
        ),
    ]
