# Generated by Django 5.2.14 on 2026-05-28 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('first_name', models.CharField(max_length=150, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='apellido')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('docente_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes_creados', to=settings.AUTH_USER_MODEL, verbose_name='docente creador')),
                ('docentes', models.ManyToManyField(blank=True, related_name='estudiantes', to=settings.AUTH_USER_MODEL, verbose_name='docentes que lo administran')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_estudiante', to=settings.AUTH_USER_MODEL, verbose_name='cuenta de usuario')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to=settings.AUTH_USER_MODEL, verbose_name='docente')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de inscripción')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='academico.estudiante')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='academico.grupo')),
            ],
            options={
                'verbose_name': 'Inscripción a grupo',
                'verbose_name_plural': 'Inscripciones a grupos',
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='grupos', through='academico.InscripcionGrupo', to='academico.estudiante', verbose_name='estudiantes'),
        ),
        migrations.AddIndex(
            model_name='estudiante',
            index=models.Index(fields=['correo'], name='academico_e_correo_2afd27_idx'),
        ),
        migrations.AddConstraint(
            model_name='inscripciongrupo',
            constraint=models.UniqueConstraint(fields=('grupo', 'estudiante'), name='unique_inscripcion_grupo_estudiante'),
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('docente', 'nombre'), name='unique_grupo_nombre_por_docente'),
        ),
    ]
