# Generated by Django 5.2.15 on 2026-06-07 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='periodo',
            field=models.CharField(blank=True, max_length=50, verbose_name='periodo académico'),
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('programa', models.CharField(blank=True, max_length=150, verbose_name='programa')),
                ('periodo', models.CharField(blank=True, max_length=50, verbose_name='periodo académico')),
                ('activo', models.BooleanField(default=True, verbose_name='activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to=settings.AUTH_USER_MODEL, verbose_name='docente')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='academico.materia', verbose_name='materia'),
        ),
        migrations.AddConstraint(
            model_name='materia',
            constraint=models.UniqueConstraint(fields=('docente', 'nombre'), name='unique_materia_nombre_por_docente'),
        ),
    ]
