# Generated by Django 5.2.14 on 2026-05-28 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('casos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('fecha_inicio', models.DateTimeField(verbose_name='fecha y hora de inicio')),
                ('fecha_fin', models.DateTimeField(verbose_name='fecha y hora de finalización')),
                ('tiempo_max_min', models.PositiveIntegerField(default=30, verbose_name='tiempo máximo de participación (min)')),
                ('lugar_fisico', models.CharField(blank=True, max_length=200, verbose_name='lugar físico')),
                ('mensaje_personalizado', models.TextField(blank=True, verbose_name='mensaje a los estudiantes')),
                ('estado', models.CharField(choices=[('SIN_INICIAR', 'Sin iniciar'), ('EN_CURSO', 'En curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='SIN_INICIAR', max_length=20, verbose_name='estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practicas', to='casos.caso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practicas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Práctica académica',
                'verbose_name_plural': 'Prácticas académicas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AutorizacionEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_acceso', models.CharField(max_length=16, unique=True, verbose_name='código de acceso')),
                ('notificado', models.BooleanField(default=False, verbose_name='notificado')),
                ('reintento_autorizado', models.BooleanField(default=False, verbose_name='puede reintentar')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='academico.estudiante')),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones', to='practicas.practica')),
            ],
            options={
                'verbose_name': 'Autorización de estudiante',
                'verbose_name_plural': 'Autorizaciones de estudiantes',
                'ordering': ['practica', 'estudiante__last_name'],
                'constraints': [models.UniqueConstraint(fields=('practica', 'estudiante'), name='unique_autorizacion_practica_estudiante')],
            },
        ),
    ]
