# Generated by Django 5.2.14 on 2026-05-28 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción breve')),
                ('desarrollo_situacional', models.TextField(blank=True, verbose_name='desarrollo situacional')),
                ('contexto_historia', models.TextField(blank=True, verbose_name='contexto / historia (storytelling)')),
                ('area_psicosocial', models.CharField(blank=True, max_length=150, verbose_name='área de psicología social')),
                ('tiempo_estimado_min', models.PositiveIntegerField(default=30, verbose_name='tiempo estimado (minutos)')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('IMPORTADO', 'Importado'), ('GENERADO_IA', 'Generado por IA'), ('EN_REVISION', 'En revisión'), ('VALIDADO', 'Validado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=20, verbose_name='estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('docente_creador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos_creados', to=settings.AUTH_USER_MODEL, verbose_name='docente creador')),
            ],
            options={
                'verbose_name': 'Caso de estudio',
                'verbose_name_plural': 'Casos de estudio',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='Escenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('narrativa', models.TextField(blank=True, verbose_name='narrativa / storytelling')),
                ('recursos_multimedia', models.JSONField(blank=True, default=list, help_text='Lista de URLs/refs a imágenes, audios o videos asociados al escenario.', verbose_name='recursos multimedia')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escenarios', to='casos.caso')),
            ],
            options={
                'verbose_name': 'Escenario',
                'verbose_name_plural': 'Escenarios',
                'ordering': ['caso', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('enunciado', models.TextField(verbose_name='enunciado')),
                ('peso', models.PositiveIntegerField(default=1, help_text='Peso relativo en la rúbrica del caso.', verbose_name='peso para calificación')),
                ('escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='casos.escenario')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['escenario', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='texto de la respuesta')),
                ('es_correcta', models.BooleanField(default=False, verbose_name='es correcta')),
                ('justificacion', models.TextField(blank=True, verbose_name='justificación')),
                ('retroalimentacion', models.TextField(blank=True, verbose_name='retroalimentación')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='casos.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['pregunta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('escala_maxima', models.PositiveIntegerField(default=100, verbose_name='puntaje máximo')),
                ('criterios', models.JSONField(blank=True, default=list, help_text='Lista de criterios: [{nombre, peso, descripcion}, ...].', verbose_name='criterios')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('caso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rubrica', to='casos.caso')),
            ],
            options={
                'verbose_name': 'Rúbrica',
                'verbose_name_plural': 'Rúbricas',
            },
        ),
        migrations.AddConstraint(
            model_name='escenario',
            constraint=models.UniqueConstraint(fields=('caso', 'orden'), name='unique_orden_por_caso'),
        ),
        migrations.AddConstraint(
            model_name='pregunta',
            constraint=models.UniqueConstraint(fields=('escenario', 'orden'), name='unique_orden_por_escenario'),
        ),
    ]
