# Generated by Django 5.2.15 on 2026-06-07 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_grupo_periodo_materia_grupo_materia_and_more'),
        ('casos', '0002_rubrica_avanzada'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos', to='academico.materia', verbose_name='materia'),
        ),
    ]
